import { Recipe } from './types';

const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Houmous Maison',
    category: 'Apéro',
    ingredients: [
      { name: 'Pois chiches', quantity: '400', unit: 'g' },
      { name: 'Tahini', quantity: '60', unit: 'ml' },
      { name: 'Citron', quantity: '1', unit: 'unité' },
      { name: 'Ail', quantity: '2', unit: 'gousses' },
      { name: 'Huile d\'olive', quantity: '60', unit: 'ml' },
    ],
    steps: [
      'Égoutter et rincer les pois chiches',
      'Mixer tous les ingrédients jusqu\'à obtenir une texture lisse',
      'Assaisonner avec sel et poivre',
      'Servir avec un filet d\'huile d\'olive',
    ],
    cookingTime: 'Court',
    nbPerson:4,
    prepTime: 10,
    difficulty: 'Facile',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Tapenade d\'Olives',
    category: 'Apéro',
    ingredients: [
      { name: 'Olives noires', quantity: '200', unit: 'g' },
      { name: 'Câpres', quantity: '2', unit: 'cuillère à soupe' },
      { name: 'Anchois', quantity: '3', unit: 'filets' },
      { name: 'Ail', quantity: '1', unit: 'gousse' },
      { name: 'Huile d\'olive', quantity: '50', unit: 'ml' },
    ],
    steps: [
      'Dénoyauter les olives',
      'Mixer tous les ingrédients',
      'Ajouter l\'huile d\'olive progressivement',
      'Réserver au frais avant de servir',
    ],
    cookingTime: 'Court',
    nbPerson:4,
    prepTime: 15,
    difficulty: 'Facile',
    image: 'https://images.unsplash.com/photo-1632843149859-ce614f683496',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Guacamole',
    category: 'Apéro',
    
    ingredients: [
      { name: 'Avocats', quantity: '3', unit: 'unité' },
      { name: 'Tomate', quantity: '1', unit: 'unité' },
      { name: 'Oignon rouge', quantity: '1', unit: 'unité' },
      { name: 'Citron vert', quantity: '1', unit: 'unité' },
      { name: 'Coriandre', quantity: '1', unit: 'bouquet' },
    ],
    steps: [
      'Écraser les avocats',
      'Couper les légumes en petits dés',
      'Mélanger tous les ingrédients',
      'Assaisonner avec sel, poivre et jus de citron',
    ],
    cookingTime: 'Court',
    nbPerson:6,
    prepTime: 15,
    difficulty: 'Facile',
    image: 'https://images.unsplash.com/photo-1615937657715-bc7b4b7962c1',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Salade César',
    category: 'Entrée',
    ingredients: [
      { name: 'Laitue romaine', quantity: '1', unit: 'unité' },
      { name: 'Poulet', quantity: '200', unit: 'g' },
      { name: 'Parmesan', quantity: '50', unit: 'g' },
      { name: 'Croûtons', quantity: '100', unit: 'g' },
      { name: 'Sauce césar', quantity: '100', unit: 'ml' },
    ],
    steps: [
      'Laver et couper la salade',
      'Griller le poulet et le couper en morceaux',
      'Préparer la sauce césar',
      'Assembler tous les ingrédients',
    ],
    cookingTime: 'Court',
    nbPerson:2,
    prepTime: 20,
    difficulty: 'Facile',
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Soupe à l\'Oignon',
    category: 'Entrée',
    ingredients: [
      { name: 'Oignons', quantity: '6', unit: 'unité' },
      { name: 'Bouillon de boeuf', quantity: '1', unit: 'l' },
      { name: 'Beurre', quantity: '50', unit: 'g' },
      { name: 'Pain', quantity: '4', unit: 'tranches' },
      { name: 'Gruyère râpé', quantity: '100', unit: 'g' },
    ],
    steps: [
      'Faire revenir les oignons dans le beurre',
      'Ajouter le bouillon et laisser mijoter',
      'Disposer le pain et le fromage',
      'Gratiner au four',
    ],
    cookingTime: 'Moyen',
    nbPerson:2,
    prepTime: 30,
    difficulty: 'Moyen',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Carpaccio de Saumon',
    category: 'Entrée',
    ingredients: [
      { name: 'Saumon frais', quantity: '400', unit: 'g' },
      { name: 'Citron', quantity: '2', unit: 'unité' },
      { name: 'Huile d\'olive', quantity: '50', unit: 'ml' },
      { name: 'Aneth', quantity: '1', unit: 'bouquet' },
      { name: 'Câpres', quantity: '30', unit: 'g' },
    ],
    steps: [
      'Trancher finement le saumon',
      'Arroser de jus de citron et d\'huile',
      'Parsemer d\'aneth et de câpres',
      'Servir très frais',
    ],
    cookingTime: 'Court',
    nbPerson:4,
    prepTime: 15,
    difficulty: 'Moyen',
    image: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: 'Poulet Rôti aux Herbes',
    category: 'Plat Principal',
    ingredients: [
      { name: 'Poulet entier', quantity: '1.5', unit: 'kg' },
      { name: 'Thym frais', quantity: '4', unit: 'branches' },
      { name: 'Romarin', quantity: '2', unit: 'branches' },
      { name: 'Ail', quantity: '6', unit: 'gousses' },
      { name: 'Beurre', quantity: '100', unit: 'g' },
    ],
    steps: [
      'Préchauffer le four à 180°C',
      'Assaisonner le poulet de sel et poivre',
      'Insérer les herbes et l\'ail sous la peau',
      'Badigeonner de beurre fondu',
      'Cuire 1h30 en arrosant régulièrement',
    ],
    cookingTime: 'Long',
    nbPerson:4,
    prepTime: 20,
    difficulty: 'Moyen',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6',
    authorId: '1',
    authorName: 'Test User',
    ratings: [],
    comments: [],
    createdAt: new Date('2024-01-01'),
  },
  // ... rest of the recipes with the same structure
];

// Update all other recipes to include the new required fields
recipes.forEach(recipe => {
  if (!recipe.ratings) recipe.ratings = [];
  if (!recipe.comments) recipe.comments = [];
  if (!recipe.authorId) recipe.authorId = '1';
  if (!recipe.authorName) recipe.authorName = 'Test User';
  if (!recipe.createdAt) recipe.createdAt = new Date('2024-01-01');
});

export { recipes };
